name: Go Build and Test, and Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  go-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'  # or any other Go version

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...


